"""
inference_session.py
--------------------
High-level session abstraction for a single inference run.

An InferenceSession orchestrates:
  1. BackendSelector  → resolve backend from hw_profile + plan
  2. ArgumentBuilder  → build CLI argument list
  3. ProcessManager   → launch subprocess, stream tokens asynchronously
  4. StatsCollector   → OS sampling (concurrent) + stderr parsing (post-run)
  5. InferenceResult  → package output + statistics

Usage
-----
    # Context manager (auto-cleanup)
    with InferenceSession(model_path, plan, config, hw_profile) as session:
        result = session.run("Describe quantum entanglement.")
        print(result.generated_text)
        print(result.stats.eval_tps, "tok/s")

    # Or direct usage
    session = InferenceSession(model_path, plan, config, hw_profile)
    result = session.run(prompt)
    session.close()
"""
from __future__ import annotations

import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from .argument_builder import ArgumentBuilder
from .backend_selector import BackendInfo, BackendSelector
from .process_manager import ProcessManager
from .runtime_config import RuntimeConfig
from .stats_collector import RuntimeStats, StatsCollector
from kv_manager import IntelligentKVManager, KVDecision, KVPolicyConfig
from layer_placement.placement_plan import PlacementPlan
from runtime_learning import LearningRecommendation, RuntimeLearningEngine
from scheduler import (
    ContextDecision,
    ContextScheduler,
    ContextSchedulerConfig,
    MemoryDecision,
    MemoryScheduler,
    MemorySchedulerConfig,
    MicrobatchScheduler,
    SchedulerConfig,
    SchedulingDecision,
)


# ---------------------------------------------------------------------------
# InferenceResult
# ---------------------------------------------------------------------------

@dataclass
class InferenceResult:
    """
    The complete output of a single inference run.

    Attributes
    ----------
    generated_text : str
        The full text generated by the model (concatenated stdout).
    stats : RuntimeStats
        Complete runtime statistics for this run.
    raw_stderr : str
        Full raw stderr output from llama.exe (useful for debugging).
    exit_code : int
        Subprocess exit code. 0 = success.
    success : bool
        True if exit_code == 0 and stats.tokens_generated > 0.
    args : List[str]
        The exact CLI argument list used to launch the subprocess.
    backend : str
        Backend name used for this run (e.g. "vulkan", "cuda", "cpu").
    scheduling_decision : Optional[SchedulingDecision]
        Microbatch scheduling decision metadata.
    context_decision : Optional[ContextDecision]
        Dynamic context scheduling decision metadata.
    memory_decision : Optional[MemoryDecision]
        Adaptive memory scheduling decision metadata.
    learning_recommendation : Optional[LearningRecommendation]
        Adaptive Runtime Intelligence recommendation metadata.
    kv_decision : Optional[KVDecision]
        Intelligent KV Manager decision metadata.
    """
    generated_text: str
    stats: RuntimeStats
    raw_stderr: str
    exit_code: int
    success: bool
    args: List[str] = field(default_factory=list)
    backend: str = "unknown"
    scheduling_decision: Optional[SchedulingDecision] = None
    context_decision: Optional[ContextDecision] = None
    memory_decision: Optional[MemoryDecision] = None
    learning_recommendation: Optional[LearningRecommendation] = None
    kv_decision: Optional[KVDecision] = None

    def to_dict(self) -> Dict[str, Any]:
        d = {
            "generated_text": self.generated_text,
            "stats": self.stats.to_dict(),
            "exit_code": self.exit_code,
            "success": self.success,
            "backend": self.backend,
        }
        if self.scheduling_decision is not None:
            d["scheduling_decision"] = self.scheduling_decision.to_dict()
        if self.context_decision is not None:
            d["context_decision"] = self.context_decision.to_dict()
        if self.memory_decision is not None:
            d["memory_decision"] = self.memory_decision.to_dict()
        if self.learning_recommendation is not None:
            d["learning_recommendation"] = self.learning_recommendation.to_dict()
        if self.kv_decision is not None:
            d["kv_decision"] = self.kv_decision.to_dict()
        return d


# ---------------------------------------------------------------------------
# InferenceSession
# ---------------------------------------------------------------------------

class InferenceSession:
    """
    Manages a single inference session against a GGUF model.

    Coordinates backend detection, CLI argument construction, subprocess
    launch with asynchronous token streaming, OS utilization sampling, and
    statistics finalization.

    Parameters
    ----------
    model_path : Path
        Path to the ``.gguf`` model file.
    plan : PlacementPlan
        Phase 3 placement plan describing where each layer should run.
    config : RuntimeConfig
        Runtime configuration (threads, flash attn, mmap, etc.).
    hw_profile : dict
        Hardware profile for backend detection and parameter lookup.
    llama_exe_path : Path, optional
        Explicit path to the llama.exe binary. If None, auto-searched from
        the project's ``build/bin/`` directory.
    """

    # Default locations to search for the llama executable
    _EXE_SEARCH_PATHS = [
        "build/bin/llama.exe",
        "build/bin/Release/llama.exe",
        "build/bin/llama",
        "build/bin/llama-cli.exe",
        "build/bin/llama-cli",
    ]

    def __init__(
        self,
        model_path: Path,
        plan: PlacementPlan,
        config: RuntimeConfig,
        hw_profile: Dict[str, Any],
        llama_exe_path: Optional[Path] = None,
    ) -> None:
        self.model_path = Path(model_path)
        self.plan = plan
        self.config = config
        self.hw_profile = hw_profile

        # Resolve llama executable
        self.llama_exe = llama_exe_path or self._find_llama_exe()

        # Resolve backend
        backend_override = config.force_backend
        self._backend_selector = BackendSelector(hw_profile, force_backend=backend_override)
        self.backend_info: BackendInfo = self._backend_selector.detect_backend(plan)

        # Build argument list builder
        self._arg_builder = ArgumentBuilder(self.llama_exe)

        # PCIe bandwidth for transfer estimation
        interconnects = hw_profile.get("interconnects", [])
        pcie_bw_gbps = 16.0
        for ic in interconnects:
            if ic.get("type", "").upper() == "PCIE":
                pcie_bw_gbps = float(ic.get("bandwidth", 16.0))
                break

        self._pcie_bandwidth_gbps = pcie_bw_gbps
        self._last_result: Optional[InferenceResult] = None
        self.memory_budget: Optional[Any] = None
        self.microbatch_scheduler = MicrobatchScheduler()
        self.scheduling_decision: Optional[SchedulingDecision] = None
        self.context_scheduler = ContextScheduler()
        self.context_decision: Optional[ContextDecision] = None
        self.memory_scheduler = MemoryScheduler()
        self.memory_decision: Optional[MemoryDecision] = None
        self.learning_engine = RuntimeLearningEngine()
        self.learning_recommendation: Optional[LearningRecommendation] = None
        self.kv_manager = IntelligentKVManager()
        self.kv_decision: Optional[KVDecision] = None

        if self.config.run_preflight_check:
            self.run_preflight_check()

    # ---------------------------------------------------------------------------
    # Public API
    # ---------------------------------------------------------------------------

    def run(
        self,
        prompt: str,
        on_token: Optional[Callable[[str], None]] = None,
    ) -> InferenceResult:
        """
        Execute a single inference pass with the given prompt.
        """
        # Adaptive Runtime Intelligence (ARTI) Recommendation
        learning_rec: Optional[LearningRecommendation] = None
        if self.config.enable_runtime_learning:
            learning_rec = self.learning_engine.get_recommendation(
                model_metadata={
                    "num_layers": self.plan.total_layers,
                    "hidden_size": getattr(self.plan, "hidden_size", 4096),
                    "model_name": self.plan.model_name,
                },
                hw_profile=self.hw_profile,
                requested_context=min(self.config.context_length, self.plan.context_length),
                backend=self.backend_info.name,
            )
            self.learning_recommendation = learning_rec
            if self.config.verbose_learning_engine:
                gpu_name = self.hw_profile.get("gpus", [{}])[0].get("name", "GPU") if self.hw_profile.get("gpus") else "CPU"
                print(learning_rec.format_cli_output(gpu_name=gpu_name, model_name=self.plan.model_name))

        # Adaptive Memory Scheduling
        memory_decision: Optional[MemoryDecision] = None
        if self.config.enable_adaptive_memory_scheduler:
            mem_cfg = MemorySchedulerConfig(
                enabled=self.config.enable_adaptive_memory_scheduler,
                vram_safety_margin=self.config.vram_safety_margin,
                ram_safety_margin=self.config.ram_safety_margin,
                memory_strategy=self.config.memory_strategy,
                oom_prevention=self.config.oom_prevention,
                verbose=self.config.verbose_memory_scheduler,
            )
            memory_decision = self.memory_scheduler.schedule_memory(
                model_metadata={
                    "num_layers": self.plan.total_layers,
                    "hidden_size": getattr(self.plan, "hidden_size", 4096),
                    "model_name": self.plan.model_name,
                },
                requested_context=min(self.config.context_length, self.plan.context_length),
                memory_plan=self.memory_budget,
                layer_placement=self.plan,
                backend=self.backend_info,
                hw_profile=self.hw_profile,
                config_override=mem_cfg,
            )
            self.memory_decision = memory_decision
            if memory_decision.suggested_microbatch_override and self.config.manual_microbatch is None:
                self.config.manual_microbatch = memory_decision.suggested_microbatch_override
            if memory_decision.suggested_context_override and self.config.manual_context is None:
                self.config.manual_context = memory_decision.suggested_context_override

        # Intelligent KV Manager Evaluation
        kv_decision: Optional[KVDecision] = None
        if self.config.enable_kv_manager:
            kv_cfg = KVPolicyConfig(
                enabled=self.config.enable_kv_manager,
                compression_enabled=self.config.kv_compression_enabled,
                eviction_enabled=self.config.kv_eviction_enabled,
                compression_mode=self.config.kv_compression_mode,
                eviction_policy=self.config.kv_eviction_policy,
                verbose=self.config.verbose_kv_manager,
            )
            gpus = self.hw_profile.get("gpus", [])
            free_vram = gpus[0].get("vram_free_mb", 8000.0) if gpus else 8000.0
            tot_vram = gpus[0].get("vram_total_mb", 16384.0) if gpus else 16384.0
            press_level = memory_decision.pressure_level if memory_decision else "Low"

            kv_decision = self.kv_manager.evaluate_kv_state(
                model_metadata={
                    "num_layers": self.plan.total_layers,
                    "hidden_size": getattr(self.plan, "hidden_size", 4096),
                    "model_name": self.plan.model_name,
                },
                context_length=self.config.context_length,
                vram_free_mb=free_vram,
                vram_total_mb=tot_vram,
                pressure_level=press_level,
                learning_recommendation=learning_rec,
                config_override=kv_cfg,
            )
            self.kv_decision = kv_decision

        # Dynamic Context Scheduling
        context_decision: Optional[ContextDecision] = None
        if self.config.enable_dynamic_context:
            ctx_cfg = ContextSchedulerConfig(
                enabled=self.config.enable_dynamic_context,
                min_context=self.config.min_context,
                max_context=self.config.max_context,
                safety_margin=self.config.context_safety_margin,
                optimization_goal=self.config.context_optimization_goal,
                manual_override=self.config.manual_context,
                verbose=self.config.verbose_context_scheduler,
            )
            req_ctx = min(self.config.context_length, self.plan.context_length)
            context_decision = self.context_scheduler.schedule_context(
                model_metadata={
                    "num_layers": self.plan.total_layers,
                    "hidden_size": getattr(self.plan, "hidden_size", 4096),
                    "model_name": self.plan.model_name,
                },
                requested_context=req_ctx,
                memory_plan=self.memory_budget,
                layer_placement=self.plan,
                backend=self.backend_info,
                hw_profile=self.hw_profile,
                config_override=ctx_cfg,
                override_context=self.config.manual_context,
            )
            self.context_decision = context_decision
            self.config.context_length = context_decision.effective_context
            if context_decision.suggested_microbatch and self.config.manual_microbatch is None:
                self.config.manual_microbatch = context_decision.suggested_microbatch

        # Dynamic Microbatch Scheduling
        decision: Optional[SchedulingDecision] = None
        selected_microbatch: Optional[int] = None
        if self.config.enable_dynamic_microbatch:
            sched_cfg = SchedulerConfig(
                enabled=self.config.enable_dynamic_microbatch,
                min_microbatch=self.config.min_microbatch,
                max_microbatch=self.config.max_microbatch,
                safety_margin=self.config.microbatch_safety_margin,
                aggressiveness=self.config.microbatch_aggressiveness,
                optimization_goal=self.config.microbatch_optimization_goal,
                manual_override=self.config.manual_microbatch,
                verbose=self.config.verbose_microbatch_scheduler,
            )
            eff_ctx = min(self.config.context_length, self.plan.context_length)
            decision = self.microbatch_scheduler.select_microbatch(
                model_metadata={
                    "num_layers": self.plan.total_layers,
                    "hidden_size": getattr(self.plan, "hidden_size", 4096),
                    "model_name": self.plan.model_name,
                },
                context_length=eff_ctx,
                memory_plan=self.memory_budget,
                layer_placement=self.plan,
                hw_profile=self.hw_profile,
                backend=self.backend_info,
                config_override=sched_cfg,
                override_microbatch=self.config.manual_microbatch,
            )
            self.scheduling_decision = decision
            selected_microbatch = decision.microbatch

        # Build argument list
        args = self._arg_builder.build(
            model_path=self.model_path,
            prompt=prompt,
            plan=self.plan,
            config=self.config,
            backend=self.backend_info,
            microbatch=selected_microbatch,
        )

        # Initialize stats collector
        collector = StatsCollector(
            sample_interval_ms=self.config.stats_sample_interval_ms,
            n_gpu_layers=self.backend_info.n_gpu_layers,
            context_length=min(self.config.context_length, self.plan.context_length),
            backend=self.backend_info.name,
            model_name=self.plan.model_name,
            boundary_crossings=self.plan.boundary_crossings,
            pcie_bandwidth_gbps=self._pcie_bandwidth_gbps,
            is_feasible=self.plan.is_feasible,
        )

        # Launch subprocess
        proc_manager = ProcessManager(env_vars=self.backend_info.env_vars)
        proc_manager.launch(args)

        wall_start = time.perf_counter()

        # Start OS sampling ASAP after process launch
        collector.start_sampling()

        stdout_text = ""
        stderr_text = ""

        if self.config.async_streaming:
            # Async path: background threads read stdout/stderr concurrently
            def _on_token(text: str, elapsed_ms: float) -> None:
                collector.record_token()
                if on_token is not None:
                    on_token(text)

            proc_manager.stream_async(on_token=_on_token)
            stdout_text, stderr_text = proc_manager.wait_for_completion(
                timeout_sec=self.config.process_timeout_sec
            )
        else:
            # Synchronous path: communicate() blocks until process exits
            stdout_text, stderr_text, _ = proc_manager.wait_sync(
                timeout_sec=self.config.process_timeout_sec
            )
            # Fire on_token for each line retroactively (no real streaming)
            if on_token is not None:
                for line in stdout_text.splitlines():
                    if line.strip():
                        on_token(line)

        wall_end = time.perf_counter()
        total_wall_ms = (wall_end - wall_start) * 1000.0

        # Stop OS sampling
        collector.stop_sampling()

        # Finalize statistics
        combined_logs = stderr_text + "\n" + stdout_text
        stats = collector.finalize(combined_logs, total_wall_ms=total_wall_ms)

        exit_code = proc_manager.return_code or 0
        success = exit_code == 0

        result = InferenceResult(
            generated_text=stdout_text,
            stats=stats,
            raw_stderr=stderr_text,
            exit_code=exit_code,
            success=success,
            args=args,
            backend=self.backend_info.name,
            scheduling_decision=decision,
            context_decision=context_decision,
            memory_decision=memory_decision,
            learning_recommendation=learning_rec,
            kv_decision=kv_decision,
        )
        self._last_result = result

        # Record post-inference execution telemetry into Runtime Learning Engine
        if self.config.enable_runtime_learning:
            self.learning_engine.record_execution(
                model_metadata={
                    "num_layers": self.plan.total_layers,
                    "hidden_size": getattr(self.plan, "hidden_size", 4096),
                    "model_name": self.plan.model_name,
                },
                hw_profile=self.hw_profile,
                stats=stats,
                args=args,
                backend=self.backend_info.name,
                n_gpu_layers=self.backend_info.n_gpu_layers,
                n_cpu_layers=self.plan.n_cpu_layers,
                n_igpu_layers=self.plan.n_igpu_layers,
                microbatch_size=selected_microbatch or 512,
                context_length=self.config.context_length,
                scheduler_decisions={
                    "microbatch": decision.to_dict() if decision else None,
                    "context": context_decision.to_dict() if context_decision else None,
                    "memory": memory_decision.to_dict() if memory_decision else None,
                },
                warnings=getattr(stats, "warnings", []),
                success=success,
                duration_sec=total_wall_ms / 1000.0,
            )

        # Record post-inference performance telemetry feedback
        if decision is not None and stats is not None:
            eff_mb = selected_microbatch or self.config.batch_size
            self.microbatch_scheduler.record_runtime_feedback(
                prompt_tps=stats.prompt_eval_tps,
                eval_tps=stats.eval_tps,
                actual_vram_mb=0.0,
                actual_ram_mb=0.0,
                gpu_util_pct=stats.avg_gpu_util_pct,
                cpu_util_pct=stats.avg_cpu_util_pct,
                ttft_ms=stats.prompt_eval_ms,
                microbatch=eff_mb,
                context_length=min(self.config.context_length, self.plan.context_length),
                model_name=self.plan.model_name,
                backend=self.backend_info.name,
            )

        return result

    @property
    def last_result(self) -> Optional[InferenceResult]:
        """The most recent InferenceResult from this session."""
        return self._last_result

    def close(self) -> None:
        """Clean up session resources (currently a no-op; reserved for future use)."""
        pass

    def run_preflight_check(self) -> Any:
        """Run Phase 6 pre-flight memory optimization analysis."""
        from runtime_memory import PreflightGuard
        from layer_placement.model_descriptor import ModelDescriptor

        model_size_bytes = self.model_path.stat().st_size if self.model_path.exists() else 4 * 1024**3
        model_desc = ModelDescriptor.from_gguf_metadata(
            metadata={
                "arch": self.plan.architecture,
                "num_layers": self.plan.total_layers,
                "max_context_length": self.plan.context_length,
            },
            model_size_bytes=model_size_bytes,
            model_name=self.plan.model_name,
        )
        guard = PreflightGuard(
            hw_profile=self.hw_profile,
            auto_resize_buffers=self.config.auto_resize_context,
            block_on_critical=self.config.block_on_critical_oom,
            backend=self.backend_info.name,
        )
        budget = guard.check(model_desc, self.plan, self.config.context_length, self.config.batch_size)
        self.memory_budget = budget
        if budget.auto_resized:
            self.config.context_length = budget.effective_context
        return budget

    def __enter__(self) -> "InferenceSession":
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        self.close()

    # ---------------------------------------------------------------------------
    # Internal helpers
    # ---------------------------------------------------------------------------

    def _find_llama_exe(self) -> Path:
        """
        Search known build output locations for the llama executable.

        Returns
        -------
        Path
            Absolute path to the found executable.

        Raises
        ------
        FileNotFoundError
            If no executable is found in any known location.
        """
        project_root = Path(__file__).parent.parent
        for rel in self._EXE_SEARCH_PATHS:
            candidate = project_root / rel
            if candidate.exists():
                return candidate

        # Fallback: walk build/bin recursively
        bin_dir = project_root / "build" / "bin"
        if bin_dir.exists():
            for f in sorted(bin_dir.rglob("llama*")):
                if f.is_file() and f.suffix not in (".a", ".lib", ".pdb"):
                    return f

        raise FileNotFoundError(
            "llama executable not found in build/bin/. "
            "Please run the build engine (setup phase) first.\n"
            f"Searched under: {project_root / 'build' / 'bin'}"
        )
