"""
Integration test for orchestrator/backend_wrapper.py

This test verifies that:
1. The wrapper can find the DLL generated by Phase 2.
2. ctypes can successfully load the DLL.
3. We can invoke llama_backend_init and llama_backend_free without crashing.
"""
import platform
from pathlib import Path
from orchestrator.backend_wrapper import load_library_from_build_result

def test_backend_wrapper_can_load_and_init():
    # Only run this if the build_result.json exists
    project_root = Path(__file__).parent.parent
    build_result_path = project_root / "build" / "build_result.json"
    
    if not build_result_path.exists():
        # Skip gracefully if the user hasn't run the build
        import pytest
        pytest.skip("build_result.json not found. Run Phase 2 build first.")
        
    # Attempt to load the library
    try:
        lib = load_library_from_build_result(build_result_path)
    except RuntimeError as e:
        import pytest
        pytest.skip(f"Shared library not present in build_result artifacts: {e}")
    
    # Verify the path looks correct based on OS
    system = platform.system()
    ext = ".dll" if system == "Windows" else ".dylib" if system == "Darwin" else ".so"
    assert lib.lib_path.suffix == ext
    assert lib.lib_path.exists()
    
    # Try calling the C functions
    try:
        lib.backend_init()
        lib.numa_init(0) # GGML_NUMA_STRATEGY_DISABLED
        lib.backend_free()
    except Exception as e:
        import pytest
        pytest.fail(f"Calling llama C-API crashed: {e}")
