"""
backend_wrapper.py
------------------
Minimal ctypes wrapper for the InferenceOS compiled llama.cpp shared library.
Unlike llama-cpp-python, this is tightly tailored for our custom inference engine,
enabling fast access to memory internals, KV cache eviction, and speculative decoding.
"""
from __future__ import annotations

import ctypes
import json
import os
import platform
import sys
from pathlib import Path


class LlamaLibrary:
    def __init__(self, lib_path: Path):
        self.lib_path = lib_path
        
        # Load the shared library
        try:
            if platform.system() == "Windows":
                # Ensure the directory is in PATH for any dependency DLLs (like ggml.dll)
                os.add_dll_directory(str(lib_path.parent.absolute()))
                
                # Also add system PATH directories to resolve MinGW runtime DLLs
                # (libstdc++-6.dll, libgcc_s_seh-1.dll, libwinpthread-1.dll)
                # In Python 3.8+, ctypes ignores the PATH env var by default.
                for p in os.environ.get("PATH", "").split(os.pathsep):
                    p_path = Path(p.strip('"'))
                    if p_path.is_dir():
                        try:
                            os.add_dll_directory(str(p_path.absolute()))
                        except Exception:
                            pass
                            
                self._lib = ctypes.CDLL(str(lib_path))
            else:
                self._lib = ctypes.CDLL(str(lib_path))
        except OSError as e:
            raise RuntimeError(f"Failed to load shared library {lib_path}: {e}")

        # --- Bindings ---
        # void llama_backend_init(void)
        self._lib.llama_backend_init.argtypes = []
        self._lib.llama_backend_init.restype = None

        # void llama_backend_free(void)
        self._lib.llama_backend_free.argtypes = []
        self._lib.llama_backend_free.restype = None
        
        # void llama_numa_init(enum ggml_numa_strategy numa)
        self._lib.llama_numa_init.argtypes = [ctypes.c_int]
        self._lib.llama_numa_init.restype = None

    def backend_init(self) -> None:
        """Initialize the llama + ggml backend."""
        self._lib.llama_backend_init()

    def backend_free(self) -> None:
        """Free the llama + ggml backend."""
        self._lib.llama_backend_free()

    def numa_init(self, strategy: int = 0) -> None:
        """Optional NUMA optimization initialization."""
        self._lib.llama_numa_init(strategy)


def load_library_from_build_result(build_result_path: Path | None = None) -> LlamaLibrary:
    """
    Reads build_result.json (generated by Phase 2) to find and load the shared library.
    """
    if build_result_path is None:
        # Default fallback relative to the project root
        build_result_path = Path(__file__).parent.parent / "build" / "build_result.json"

    if not build_result_path.exists():
        raise FileNotFoundError(
            f"build_result.json not found at {build_result_path}. "
            "Please run the Phase 2 build engine first."
        )

    with open(build_result_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    artifacts = data.get("artifacts_found", [])
    
    # Find the shared library among the artifacts
    lib_path = None
    system = platform.system()
    ext = ".dll" if system == "Windows" else ".dylib" if system == "Darwin" else ".so"
    
    for a in artifacts:
        p = Path(a)
        if p.suffix == ext and "llama" in p.name:
            lib_path = p
            break
            
    if not lib_path or not lib_path.exists():
        raise RuntimeError(f"Could not find a valid {ext} library in build artifacts: {artifacts}")

    return LlamaLibrary(lib_path)
