"""
recommendation.py
-----------------
LearningRecommendation data structure for Adaptive Runtime Intelligence (ARTI) in InferenceOS.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class LearningRecommendation:
    """
    Recommendation generated by Adaptive Runtime Intelligence based on historical execution data.

    Attributes
    ----------
    recommended_microbatch : Optional[int]
        Optimal learned prefill microbatch size.
    recommended_context : Optional[int]
        Optimal learned safe context window size.
    recommended_gpu_layers : Optional[int]
        Optimal learned GPU layer offload count.
    recommended_safety_margin_mb : Optional[float]
        Optimal learned unallocated VRAM safety headroom in MB.
    expected_prompt_tps : float
        Predicted prompt processing throughput (tokens/sec).
    expected_eval_tps : float
        Predicted generation throughput (tokens/sec).
    expected_ttft_ms : float
        Predicted Time To First Token in milliseconds.
    expected_vram_mb : float
        Predicted total VRAM consumption in MB.
    expected_ram_mb : float
        Predicted total system RAM consumption in MB.
    expected_gpu_utilization : float
        Predicted GPU utilization percentage.
    expected_cpu_utilization : float
        Predicted CPU utilization percentage.
    confidence : float
        Confidence score between 0.0 (cold start / no history) and 0.99 (high confidence).
    sample_count : int
        Number of historical executions analyzed to generate this recommendation.
    decision_source : str
        Source descriptor ("Runtime Learning" vs "Heuristic Fallback").
    reasoning : List[str]
        Human-readable decision explanation.
    timestamp : float
        Epoch timestamp when recommendation was computed.
    """

    recommended_microbatch: Optional[int] = None
    recommended_context: Optional[int] = None
    recommended_gpu_layers: Optional[int] = None
    recommended_safety_margin_mb: Optional[float] = None
    expected_prompt_tps: float = 0.0
    expected_eval_tps: float = 0.0
    expected_ttft_ms: float = 0.0
    expected_vram_mb: float = 0.0
    expected_ram_mb: float = 0.0
    expected_gpu_utilization: float = 0.0
    expected_cpu_utilization: float = 0.0
    confidence: float = 0.0
    sample_count: int = 0
    decision_source: str = "Heuristic Fallback"
    reasoning: List[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        """Convert recommendation to a JSON-serializable dictionary."""
        return {
            "recommended_microbatch": self.recommended_microbatch,
            "recommended_context": self.recommended_context,
            "recommended_gpu_layers": self.recommended_gpu_layers,
            "recommended_safety_margin_mb": self.recommended_safety_margin_mb,
            "expected_prompt_tps": round(self.expected_prompt_tps, 2),
            "expected_eval_tps": round(self.expected_eval_tps, 2),
            "expected_ttft_ms": round(self.expected_ttft_ms, 2),
            "expected_vram_mb": round(self.expected_vram_mb, 2),
            "expected_ram_mb": round(self.expected_ram_mb, 2),
            "expected_gpu_utilization": round(self.expected_gpu_utilization, 1),
            "expected_cpu_utilization": round(self.expected_cpu_utilization, 1),
            "confidence": round(self.confidence, 3),
            "sample_count": self.sample_count,
            "decision_source": self.decision_source,
            "reasoning": list(self.reasoning),
            "timestamp": self.timestamp,
        }

    def format_cli_output(self, gpu_name: str = "GPU", model_name: str = "Model") -> str:
        """
        Format details into the exact CLI representation required by InferenceOS.
        """
        conf_pct = int(round(self.confidence * 100.0))
        lines = [
            "Adaptive Runtime Intelligence",
            "Hardware",
            f"  {gpu_name}",
            "Model",
            f"  {model_name}",
            "Confidence",
            f"  {conf_pct}%",
            "Recommendations",
        ]
        if self.recommended_gpu_layers is not None:
            lines.extend(["  Placement", f"    {self.recommended_gpu_layers} GPU"])
        if self.recommended_microbatch is not None:
            lines.extend(["  Microbatch", f"    {self.recommended_microbatch}"])
        if self.recommended_context is not None:
            lines.extend(["  Context", f"    {self.recommended_context}"])

        lines.extend([
            "  Expected TPS",
            f"    {self.expected_eval_tps:.1f}",
            "  Expected TTFT",
            f"    {int(round(self.expected_ttft_ms))} ms",
            "Decision Source",
            f"  {self.decision_source}",
        ])
        return "\n".join(lines)
