"""
acceptance_sampler.py
---------------------
Token acceptance logic for Phase 5 Speculative Decoding Suite.

Provides two acceptance strategies for evaluating draft tokens against the
base model's probability distribution:

  1. **Greedy acceptance** — Accept a draft token if and only if it equals the
     base model's argmax (top-1) token.  This is mathematically equivalent to
     standard greedy decoding: the speculative output is identical to what the
     base model would have generated without speculation.  Zero quality loss.

  2. **Speculative sampling** — Accept draft token ``x`` with probability
     min(1, p_base(x) / p_draft(x)).  When rejected, resample from a corrected
     residual distribution (Chen et al., 2023 — "Accelerating Large Language
     Model Decoding with Speculative Sampling").  Produces samples from exactly
     the base model distribution.

Since InferenceOS uses llama.cpp as a subprocess rather than as an in-process
Python library, we do not have direct access to per-token logit tensors.  The
acceptance sampler therefore operates in **greedy mode by default**, comparing
the draft tokens against the decoded text output of a llama.cpp verification
run.

The ``verify_greedy()`` method is the primary integration point:  it receives
the model-generated text token stream and the draft token IDs, and returns
how many leading draft tokens were accepted consecutively.
"""
from __future__ import annotations

import logging
import random
from typing import List, Optional, Sequence, Tuple

logger = logging.getLogger("InferenceOS.SpeculativeDecoding.AcceptanceSampler")


class AcceptanceSampler:
    """
    Accepts or rejects speculative draft tokens based on base model output.

    Parameters
    ----------
    strategy : str
        ``"greedy"`` (default) or ``"speculative"``.
    acceptance_threshold : float
        Minimum acceptance probability for the ``"speculative"`` strategy.
        Tokens below this threshold are always rejected.  Default 0.0 (no floor).
    """

    def __init__(
        self,
        strategy: str = "greedy",
        acceptance_threshold: float = 0.0,
    ) -> None:
        valid = {"greedy", "speculative"}
        if strategy not in valid:
            raise ValueError(f"Acceptance strategy must be one of {valid}")
        self.strategy = strategy
        self.acceptance_threshold = acceptance_threshold

        # Telemetry
        self.total_drafts_evaluated: int = 0
        self.total_drafts_accepted: int = 0

    # ------------------------------------------------------------------
    # Primary API — text-level verification (subprocess integration)
    # ------------------------------------------------------------------

    def verify_greedy_text(
        self,
        draft_token_strings: Sequence[str],
        model_output_text: str,
    ) -> Tuple[int, str]:
        """
        Compare draft token strings against the model's actual output text.

        Returns the number of leading draft tokens that match the model output
        as a prefix, and the bonus token (first token produced beyond the last
        accepted draft).

        This method is used when we have the model's decoded text output from
        a llama.cpp subprocess rather than raw logit tensors.

        Parameters
        ----------
        draft_token_strings : sequence of str
            Candidate draft tokens as decoded strings (e.g. ``[" the", " cat"]``).
        model_output_text : str
            Full text generated by the base model in the verification pass.

        Returns
        -------
        (n_accepted, bonus_token) : tuple of (int, str)
            ``n_accepted`` — number of draft tokens accepted (0 … len(drafts)).
            ``bonus_token`` — the next model token after the last accepted draft
                              (may be empty string if model produced nothing extra).
        """
        self.total_drafts_evaluated += len(draft_token_strings)

        if not draft_token_strings or not model_output_text:
            return 0, model_output_text

        # Reconstruct the draft concatenation and check prefix match
        draft_concat = "".join(draft_token_strings)

        n_accepted = 0
        consumed_len = 0

        for tok in draft_token_strings:
            end_pos = consumed_len + len(tok)
            if model_output_text[consumed_len:end_pos] == tok:
                n_accepted += 1
                consumed_len = end_pos
            else:
                break

        # Bonus token: text after the last accepted draft token
        bonus = model_output_text[consumed_len:] if consumed_len <= len(model_output_text) else ""

        self.total_drafts_accepted += n_accepted
        logger.debug(
            "AcceptanceSampler: %d/%d drafts accepted  bonus=%r",
            n_accepted, len(draft_token_strings), bonus[:20],
        )
        return n_accepted, bonus

    # ------------------------------------------------------------------
    # Token-ID level verification (for in-process llama-python bindings)
    # ------------------------------------------------------------------

    def verify_greedy_ids(
        self,
        draft_ids: Sequence[int],
        verified_ids: Sequence[int],
    ) -> Tuple[int, Optional[int]]:
        """
        Compare draft token IDs against verified base-model token IDs.

        Greedy mode: accept the longest prefix of draft_ids that matches the
        corresponding prefix of verified_ids.

        Parameters
        ----------
        draft_ids : sequence of int
            Speculative draft token IDs.
        verified_ids : sequence of int
            Token IDs produced by the base model's verification forward pass
            (same length or longer than draft_ids).

        Returns
        -------
        (n_accepted, bonus_id) : tuple of (int, int or None)
        """
        self.total_drafts_evaluated += len(draft_ids)

        n_accepted = 0
        for d, v in zip(draft_ids, verified_ids):
            if d == v:
                n_accepted += 1
            else:
                break

        bonus_id: Optional[int] = None
        if n_accepted < len(verified_ids):
            bonus_id = verified_ids[n_accepted]

        self.total_drafts_accepted += n_accepted
        return n_accepted, bonus_id

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------

    @property
    def acceptance_rate(self) -> float:
        """Overall fraction of evaluated draft tokens that were accepted."""
        return self.total_drafts_accepted / max(1, self.total_drafts_evaluated)

    def get_stats(self) -> dict:
        return {
            "strategy": self.strategy,
            "total_drafts_evaluated": self.total_drafts_evaluated,
            "total_drafts_accepted": self.total_drafts_accepted,
            "acceptance_rate": round(self.acceptance_rate, 4),
        }

    def reset_stats(self) -> None:
        """Reset telemetry counters (e.g. between benchmark runs)."""
        self.total_drafts_evaluated = 0
        self.total_drafts_accepted = 0
